# Generated by Django 4.2.8 on 2023-12-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Jaipur', 'Jaipur'), ('dholpur', 'dholpur'), ('udaipur', 'udaipur'), ('ajmer', 'ajmer')], max_length=100)),
                ('skill', models.CharField(choices=[('python', 'python'), ('c', 'c'), ('java', 'java'), ('oops', 'oops')], max_length=100)),
            ],
        ),
    ]
